name: Dependency Submission

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-24.04
    env:
      GEOMAN_DIR: ${{ github.workspace }}/maplibre-geoman-android/app
    steps:
      - uses: actions/checkout@v7

      - name: Set up build environment
        uses: ./.github/actions/setup-build-env

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4